### ISSUE TITLE
Fixing Knight interpreter written in Knight link

### ISSUE THREAD

**Issue by HoangTuan110** [knight-lang/knight-lang#10]
On the main page, there's a link to the Knight interpreter, written in Knight, that links to [https://github.com/knight-lang/knight/knight.kn](https://github.com/knight-lang/knight/knight.kn), which is broken, as the correct link is [https://github.com/knight-lang/knight-lang/blob/master/knight.kn](https://github.com/knight-lang/knight-lang/blob/master/knight.kn).

**Comment by sampersand** [comment]
Fixed, forgot to close the issue :+1:
