### ISSUE TITLE
Negative number literals

### ISSUE THREAD

**Issue by gitonthescene** [knight-lang/knight-lang#11]
Does this from section [2.2.1](https://github.com/knight-lang/knight-lang/blob/master/specs.md#221-contexts)
match the comments about numbers in section [1.3](https://github.com/knight-lang/knight-lang/blob/master/specs.md#13-number)?

> An optional - may then appear to force the number to be negative

I.e. are there actually no negative number literals in Knight?  Or is it that you can parse a - when converting from a string but not place one in the actual tokenizing?

**Comment by gitonthescene** [comment]
Not related but there's a small typo in [4.1.4](https://github.com/knight-lang/knight-lang/blob/master/specs.md#414-prompt)
>　until the \n character is encountered, ___of___ an EOF occurs

**Comment by gitonthescene** [comment]
I'm also a little confused by the [Guessing Game example](https://github.com/knight-lang/knight-lang#examples).  I thought [RAND](https://github.com/knight-lang/knight-lang/blob/master/specs.md#415-random) had arity 0.  I'm not clear how `RAND 1 max` is supposed to work.  Did the spec change?  I can see how having a clear range for the random number matters, though.

**Comment by gitonthescene** [comment]
Also a small typo in section [4](https://github.com/knight-lang/knight-lang/blob/master/specs.md#4-functions).
> Every function in Knight has a predetermined arity—there are no ___varidict___ functions.
Please do let me know if you’d rather I open up separate issues for these.

**Comment by gitonthescene** [comment]
Small point, but I think the arg spec for the second argument to [*](https://github.com/knight-lang/knight-lang/blob/master/specs.md#433-unchanged-integer) should be `number` instead of `integer`.

**Comment by gitonthescene** [comment]
Might it be slightly clearer to make [this](https://github.com/knight-lang/knight-lang/blob/master/specs.md#4310-unchanged-unevaluated) say "___evaluated___ and coerced"?
>If the first argument, after being coerced to a boolean, is FALSE, then the "uncoerced" first argument is returned. Otherwise, the second argument is evaluated and returned.

It's definitely implied that the second arg isn't evaluated, but the emphasis in the first sentence seems to be more about coercion which I think is supposed to happen after evaluation.

**Comment by gitonthescene** [comment]
Do we need the definitions of tab, carriage return, etc. [here](https://github.com/knight-lang/knight-lang/blob/master/specs.md#221-contexts)?  I'm assuming this was added before the explanation was put in the body of __numeric contexts__.  If not I'm not sure why this is here.

**Comment by gitonthescene** [comment]
I think you want "coerced to a ___string___" [here](https://github.com/knight-lang/knight-lang/blob/master/specs.md#437-unchanged-coerce)
> String: Whether or not the first argument is lexicographically smaller than the second, which is coerced to a ___number___, is returned.

**Comment by gitonthescene** [comment]
[Here](https://github.com/knight-lang/knight-lang/blob/master/specs.md#451-substitutestring-number-number-string) the function is called `SUBSTITUTE`, but the example uses `SET`.
> that is, ___SET___ "abc" 0 1 "2" should return the "2bc"

**Comment by gitonthescene** [comment]
Least important of all, [fizzbuzz.kn](https://github.com/knight-lang/knight-lang/blob/master/examples/fizzbuzz.kn) and [fizzbuzz-min.kn](https://github.com/knight-lang/knight-lang/blob/master/examples/fizzbuzz-min.kn) produce different results.  They match if you switch 3 and 5 in fizzbuzz.kn.

**Comment by gitonthescene** [comment]
I'm not able to parse the second quine example.  It looks like there are an odd number of double quotes from [line 11](https://github.com/knight-lang/knight-lang/blob/master/examples/quine.kn#L11) to line 14.  Is the double quote on line 11 a stray?  Should it be closed on line 14?

**Comment by gitonthescene** [comment]
Not related (not that any of this was) but I'm working on a Continuation Passing Style compiler for Knight so that QUIT doesn't have get passed back up the stack.  As a side effect, it probably makes it possible to write a Knight debugger.  :)  I might try that out just for the exercise.  Thanks again for posting this.  It's great inspiration.

**Comment by sampersand** [comment]
Hi! Sorry, I was away on vacation. I'll answer your questions one by one:
- It depends on how the implementation decides to parse `~1`. Implementations are free to interpret that as the `~` function with a single argument—`1`. But, if the implementation wanted to be a bit smarter about its parsing, it could parse `~1` as the integer literal `-1`. To Knight programs, it'd be identical. (Same thing with `TRUE`/`FALSE`/`NULL`: They can either be nilary functions which return a value, or you could just parse them as literals. It'd be identical.) The only time `-1` means "negative one" is when you're converting a string to an integer.
- Fixed the typo, thanks
- Oh, you're entirely correct! `RAND` used to take two arguments, and `PROMPT` used to take one. I guess I forgot to update the README when I changed it before the first release. Thanks! (Also, fixed the typo)
- What do you mean by https://github.com/knight-lang/knight-lang/issues/11#issuecomment-1207153237?
- `evaluated and coerced` is now used, I like that phrashing more.
- For the numeric conversion stuff, I thoguht it best to make it explicit, but looking at it now, I see your point, and I think it'd make it clearer to not repeat.
- For the longest time I've been meaning to clean up the examples, thanks for reminding me.
- Nice! I wrote the rust version with the intention that you could toggle all the different forms of validity; similar ideas.

Thanks for all the comments, and the sharp eyes @gitonthescene! I really appreciate it

**Comment by gitonthescene** [comment]
No worries at all.  I was worried it came across as spamming but I figured it best to capitalize when I notice stuff.

I think I get now that the minus thing is explicitly about converting strings to numbers.  In such cases it seems you’re not expecting code but rather “strings that sort of look like integers”.

The comment you linked to had a link under * to section 4.3.3 which used to say “integer” and not “number”.  That is, if we’re still in sync.  It looks like it doesn’t now and so all good.

Thanks for getting back so promptly.  I hope you had fun on safari.

**Comment by gitonthescene** [comment]
Incidentally, [both K implementations](https://github.com/gitonthescene/k-night ) are under 5000 bytes.   Do I win a prize? ;)

**Comment by gitonthescene** [comment]
Oh, maybe you were asking about the second part of the linked comment.  I probably should have simply said ‘you can remove the “is” before “true” here’

> Boolean: Whether the first argument is false and the second argument is, when coerced to a boolean, is true is returned.

**Comment by sampersand** [comment]
Ah, I se what you mean. Cool, I'll fix that.

**Comment by sampersand** [comment]
Heh, I love the K version :-)

**Comment by gitonthescene** [comment]
BTW, I was trying to make sense of this [golf solution in Knight](https://codegolf.stackexchange.com/questions/77866/numbers-with-rotational-symmetry) and as is pointed out in the comments it doesn't conform to v1.2 of the spec.  It made me wonder if it's worth posting the earlier version of the spec somewhere just to be able to convert code like this.

**Comment by sampersand** [comment]
Version 1.0 and 1.1 of the spec simply didn't include the `A` and `~` functions. One of the problems I've found is that some details are definitely implementation-specific: For example, some implementations just coerce the first argument of `-` to an integer. This is a totally valid way to do it (as only an integer for the first argument is defined behaviour), but relying on it can cause soem confusion.

The rust version has a way to ensure that your code is 100% spec compliant, but I'm not sure if it's entirely stable. I need to do a final pass over it

**Comment by gitonthescene** [comment]
I think the issue with the golf code is that it does `GET s 1 LENGTH s` when the length of `s` is one.  The spec says the following in section 4.4.2:
> If the starting index is larger than the length of the string, the behaviour is undefined.

I think with zero indexing it should be “_greater than or equal_” and not “larger”.  In this case it’s getting _from_ index 1 but that’s outside the bounds of the string.

I think the code also seems to think the second arg is an index and not a length.

**Comment by sampersand** [comment]
Ah yes, you're right about the greater than or equal, I'll ammend that. 

And yes, I think they thought the second was an index too

**Comment by achow0** [comment]
Hi, I am the person who posted the golf solution that you mention. I do realize that `Gs 1Ls` is not fully spec compliant as (1+length of the string) would be larger than the length of the string, but I use this anyways because it seems to work fine for some interpreters that I've tried, and also because it was mentioned in this [code golf tips post](https://codegolf.stackexchange.com/a/250766/96039). If you go to my post now, you will see that I've changed that section of the code to `SsF1''`, which is fully spec compliant.

**Comment by gitonthescene** [comment]
@achow0 - As you pointed out in the golf answer, the compliant version is the same number of characters.  @sampersand already replied to that thread, but maybe you want to mention this fact there.

**Comment by gitonthescene** [comment]
Should I add my K implementation to the Community link?

**Comment by sampersand** [comment]
Sure, just submit a pr
