### ISSUE TITLE
Not updated implementations

### ISSUE THREAD

**Issue by achow0** [knight-lang/knight-lang#12]
I went through some of the implementations listed in the readme and it seems like some of them are not fully updated to the newest version. For example, I looked through the source code for the javascript implementation and it seems like it's missing the `ASCII` function and unary negation `~`. I was wondering if that table could be updated to reflect the version of each of the implementations, and indicate which ones are fully up-to-date with the current version of Knight.

**Comment by sampersand** [comment]
That's a really good idea. After I finish with knight2.0, I'll go through and update the table, and note roughly how stable I think the different implementations are.

**Comment by sampersand** [comment]
I've updated it by mentioning which versions are there
