### ISSUE TITLE
No `NUCLEAR_MISSILE` function

### ISSUE THREAD

**Issue by euppal** [knight-lang/knight-lang#2]
There is a serious flaw in Knight: the absence of a `NUCLEAR_MISSILE` function. There are many reasons why this is detrimental to a coherent user experience conducive to rapid and safe development.

1. `N` is not taken
The letter `N` is free for new built-in functions

Due to these many reasons and a plethora more, Knight should definitely add the `NUCLEAR_MISSILE` function.

**Comment by euppal** [comment]
It has come to my attention that `NULL` exists. I propose `NULL` to be replaced with this.

**Comment by fennecdjay** [comment]
I strongly support this proposition.
Not to mention the very presence of `NULL` sounds like a flaw, while every *want to be* dictator would for sure adopt a language with a `NUCLEAR_MISSILE` function.

**Comment by sampersand** [comment]
I don't think most users have a use for nuclear missles.

That being said, the `X` function does exist for a reason—maybe make an `XTREME_NUCLEAR_MISSILE`?

**Comment by euppal** [comment]
I cannot believe you fail to see how essential this facility is to a complete language. I'd say that without a nuclear missile function, Knight cannot be considered a real language.
