### ISSUE TITLE
Ascii conversion

### ISSUE THREAD

**Issue by easyaspi314** [knight-lang/knight-lang#4]
Currently, unless I'm mistaken, there doesn't appear to be a reasonable way to convert to/from ASCII values. 

Therefore, I suggest the `ASCII` function.

`ASCII(x)` will convert Number to a String with the ASCII codepoint, and String to the ASCII value of the first character. (Or make it UB to call on a string with a length of > 1).

If called on an empty string, it will return the value `0`, and vice versa.

~~All non-Number types will be coerced to String.~~ It is undefined behavior to call on an object that isn't String or Number.

It is undefined behavior if the result is outside the Knight ASCII subset.
```
= g ASCII('g') # -> Number(102)
= h ASCII("hello") # => Number(103) (or UB)
= i ASCII(104) # => String("i")
= ub ASCII(NULL)  # => undefined
= ub ASCII(3847338) # => undefined
# if coercion didn't exist
; = atoi BLOCK {
   ; = sum 0
   ; = input PROMPT
   ; WHILE ? (= tmp - ASCII(input) ASCII('0')) % (tmp 10)
      ; = input SUBSTITUTE(input 0 1 "")
      : = sum + * 10 sum tmp
   : OUTPUT sum
}

```

**Comment by sampersand** [comment]
I like the idea of an ASCII function, though I'm not sure if I want it in the standard _just_ yet. Maybe as an easy-to-implement extension method, like unary minus (`~`)?

As for its behaviour, why no make it undefined behaviour to call it with anything other than a string with one character (though impls could simply take the first char, ignoring it if the string's longer) or a number where its ASCII value is a valid Knight source code character? That way it'll work like the other funcitons which dont coerce the first argument (such as `+`).

**Comment by sampersand** [comment]
I thought about it, and for languages like AWK which don't have immediate access to this, they can simply write out _all_ the valid ascii characters and index into it. with that, i think it's technically possible to implement in all supported languages.
